stages:
- test

services:
- name: postgres:15.4

include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml
- template: Jobs/Code-Quality.gitlab-ci.yml

variables:
  POSTGRES_DB: "$APP_DB_NAME"
  POSTGRES_USER: "$APP_DB_USER"
  POSTGRES_PASSWORD: "$APP_DB_PASS"
  POSTGRES_HOST_AUTH_METHOD: trust

  TEST_DB_HOST: "$APP_DB_HOST"
  TEST_DB_PORT: "$APP_DB_PORT"
  TEST_DB_NAME: "$APP_TEST_DB_NAME"
  TEST_DB_USER: "$APP_DB_USER"
  TEST_DB_PASSWORD: "$APP_DB_PASS"

lint-format-tests:
  stage: test
  image: python:3.11
  script:
  - apt-get update -qy
  - apt-get install -y python3.11
  - curl -sSL https://pdm-project.org/install-pdm.py | python3 -
  - export PATH=/root/.local/bin:$PATH
  - pdm install --dev
  - apt-get install -y postgresql-client
  - psql --host=$APP_DB_HOST --username=$APP_DB_USER --dbname=$APP_DB_NAME -c "CREATE DATABASE $APP_TEST_DB_NAME;"
  - pip install pre-commit
  - pre-commit run --all-files

sast:
  stage: test

code_quality:
  stage: test
  services:
