FROM python:3.11-slim
WORKDIR /app

ENV PYTHONPATH /app/backend

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ ./backend
COPY migration/ ./migration
COPY alembic.ini ./

EXPOSE 80
