"""refactor: Project model article element fields - 3

Revision ID: 05648e9c5742
Revises: 7e6585b55892
Create Date: 2023-12-22 12:58:23.083070

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05648e9c5742"
down_revision: Union[str, None] = "7e6585b55892"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project",
        "parse_last_article",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project",
        "parse_last_article",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###
