"""chore: change table name for LogEntry model

Revision ID: 05a0716671bd
Revises: d881c503a17f
Create Date: 2024-01-17 11:49:02.989857

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "05a0716671bd"
down_revision: Union[str, None] = "d881c503a17f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "log_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column("level", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "logger_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "message", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_log_entry_level"), "log_entry", ["level"], unique=False
    )
    op.create_index(
        op.f("ix_log_entry_logger_name"),
        "log_entry",
        ["logger_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_log_entry_message"), "log_entry", ["message"], unique=False
    )
    op.drop_index("ix_logentry_level", table_name="logentry")
    op.drop_index("ix_logentry_logger_name", table_name="logentry")
    op.drop_index("ix_logentry_message", table_name="logentry")
    op.drop_table("logentry")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "logentry",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("level", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "logger_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "message", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="logentry_pkey"),
    )
    op.create_index(
        "ix_logentry_message", "logentry", ["message"], unique=False
    )
    op.create_index(
        "ix_logentry_logger_name", "logentry", ["logger_name"], unique=False
    )
    op.create_index("ix_logentry_level", "logentry", ["level"], unique=False)
    op.drop_index(op.f("ix_log_entry_message"), table_name="log_entry")
    op.drop_index(op.f("ix_log_entry_logger_name"), table_name="log_entry")
    op.drop_index(op.f("ix_log_entry_level"), table_name="log_entry")
    op.drop_table("log_entry")
    # ### end Alembic commands ###
