"""feat: add Settings relationship to PublishArticleStatus - 2

Revision ID: 0c4503ffeb72
Revises: 4209b3843936
Create Date: 2023-12-24 17:46:10.033293

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0c4503ffeb72"
down_revision: Union[str, None] = "4209b3843936"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
