"""feat: refactor settings model

Revision ID: 10fff852e8ad
Revises: 3cc0490556c7
Create Date: 2023-12-20 20:28:03.794322

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10fff852e8ad"
down_revision: Union[str, None] = "3cc0490556c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "setting", "active", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_constraint("unique_name_project", "setting", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_name_project", "setting", ["name", "project_id"]
    )
    op.alter_column(
        "setting", "active", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###
