"""refactor: Peoject model active default status

Revision ID: 165969e2c863
Revises: 91ac56df81dc
Create Date: 2023-12-21 14:40:44.340076

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "165969e2c863"
down_revision: Union[str, None] = "91ac56df81dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project", "active", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project", "active", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###
