"""refactor: Projects model

Revision ID: 33a5a963a899
Revises: 96a77c93d7a5
Create Date: 2023-12-18 14:00:33.266903

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "33a5a963a899"
down_revision: Union[str, None] = "96a77c93d7a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
