"""init: 2

Revision ID: 3cc0490556c7
Revises: 37a4ebe726e0
Create Date: 2023-12-20 15:01:43.712922

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "3cc0490556c7"
down_revision: Union[str, None] = "37a4ebe726e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
