"""feat: add publish_article_link field to the PublishArticleStatus

Revision ID: 413a36fd368f
Revises: e3736920fcd3
Create Date: 2024-01-18 12:35:26.316855

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "413a36fd368f"
down_revision: Union[str, None] = "e3736920fcd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "publish_article_status",
        sa.Column(
            "publish_article_link",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("publish_article_status", "publish_article_link")
    # ### end Alembic commands ###
