"""feat: add Settings relationship to PublishArticleStatus

Revision ID: 4209b3843936
Revises: e8763fd0e264
Create Date: 2023-12-24 17:33:01.833529

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4209b3843936"
down_revision: Union[str, None] = "e8763fd0e264"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
