"""feat: change type for Article project field

Revision ID: 59f2deae0d7c
Revises: 666e5e337a95
Create Date: 2024-01-16 16:23:54.879227

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "59f2deae0d7c"
down_revision: Union[str, None] = "666e5e337a95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
