"""refactor: setting field in Project model - 2

Revision ID: 687e2b745964
Revises: 6bc3e1146812
Create Date: 2023-12-21 14:52:33.113067

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "687e2b745964"
down_revision: Union[str, None] = "6bc3e1146812"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
