"""refactor: setting field in Project model

Revision ID: 6bc3e1146812
Revises: bbc3e2702705
Create Date: 2023-12-21 14:51:40.298622

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "6bc3e1146812"
down_revision: Union[str, None] = "bbc3e2702705"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
