"""refactor: Project model article element fields

Revision ID: 7e6585b55892
Revises: 4ee7851ec8a4
Create Date: 2023-12-22 12:36:56.038480

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7e6585b55892"
down_revision: Union[str, None] = "4ee7851ec8a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("parse_last_article", sa.Integer(), nullable=True)
    )
    op.add_column(
        "project",
        sa.Column("parse_article_url_element", sa.JSON(), nullable=True),
    )
    op.add_column(
        "project",
        sa.Column("parse_article_img_element", sa.JSON(), nullable=True),
    )
    op.add_column(
        "project",
        sa.Column("parse_article_body_element", sa.JSON(), nullable=True),
    )
    op.drop_column("project", "parse_material_body_element")
    op.drop_column("project", "parse_material_url_element")
    op.drop_column("project", "parse_material_id_element")
    op.drop_column("project", "parse_last_material")
    op.drop_column("project", "parse_material_img_element")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "parse_material_img_element",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "project",
        sa.Column(
            "parse_last_material",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "project",
        sa.Column(
            "parse_material_id_element",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "project",
        sa.Column(
            "parse_material_url_element",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "project",
        sa.Column(
            "parse_material_body_element",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("project", "parse_article_body_element")
    op.drop_column("project", "parse_article_img_element")
    op.drop_column("project", "parse_article_url_element")
    op.drop_column("project", "parse_last_article")
    # ### end Alembic commands ###
