"""feat: add config fields for Project model

Revision ID: 91ac56df81dc
Revises: 10fff852e8ad
Create Date: 2023-12-21 14:38:17.477855

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91ac56df81dc"
down_revision: Union[str, None] = "10fff852e8ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "parse_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.add_column(
        "project",
        sa.Column("parse_last_material", sa.Integer(), nullable=False),
    )
    op.add_column(
        "project",
        sa.Column(
            "parse_material_id_element",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    op.add_column(
        "project",
        sa.Column(
            "parse_material_url_element",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    op.add_column(
        "project",
        sa.Column(
            "parse_material_img_element",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    op.add_column(
        "project",
        sa.Column(
            "parse_material_body_element",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "parse_material_body_element")
    op.drop_column("project", "parse_material_img_element")
    op.drop_column("project", "parse_material_url_element")
    op.drop_column("project", "parse_material_id_element")
    op.drop_column("project", "parse_last_material")
    op.drop_column("project", "parse_type")
    # ### end Alembic commands ###
