"""feat: add status_text field to PublishArticleStatus model

Revision ID: b98a625b6986
Revises: 59f4517df2fe
Create Date: 2023-12-25 15:30:17.159312

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b98a625b6986"
down_revision: Union[str, None] = "59f4517df2fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "publisharticlestatus",
        sa.Column(
            "status_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("publisharticlestatus", "status_text")
    # ### end Alembic commands ###
