"""refactor: Peoject model

Revision ID: bbc3e2702705
Revises: 165969e2c863
Create Date: 2023-12-21 14:47:35.050563

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "bbc3e2702705"
down_revision: Union[str, None] = "165969e2c863"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
