"""refactor: setting field in Project model - 3

Revision ID: d87e7c386e9e
Revises: 687e2b745964
Create Date: 2023-12-21 14:53:38.624706

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d87e7c386e9e"
down_revision: Union[str, None] = "687e2b745964"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
