"""feat: add LogEntry model

Revision ID: d881c503a17f
Revises: 59f2deae0d7c
Create Date: 2024-01-17 11:21:22.592543

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d881c503a17f"
down_revision: Union[str, None] = "59f2deae0d7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "logentry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column("level", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "logger_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "message", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_logentry_level"), "logentry", ["level"], unique=False
    )
    op.create_index(
        op.f("ix_logentry_logger_name"),
        "logentry",
        ["logger_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_logentry_message"), "logentry", ["message"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_logentry_message"), table_name="logentry")
    op.drop_index(op.f("ix_logentry_logger_name"), table_name="logentry")
    op.drop_index(op.f("ix_logentry_level"), table_name="logentry")
    op.drop_table("logentry")
    # ### end Alembic commands ###
