"""chore: change table name for PublishArticleStatus model

Revision ID: e3736920fcd3
Revises: 05a0716671bd
Create Date: 2024-01-17 12:02:58.363959

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e3736920fcd3"
down_revision: Union[str, None] = "05a0716671bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "publish_article_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("setting_id", sa.Integer(), nullable=False),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "status_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("try_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["article.id"],
        ),
        sa.ForeignKeyConstraint(
            ["setting_id"],
            ["setting.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "article_id", "setting_id", name="unique_article_setting"
        ),
    )
    op.drop_table("publisharticlestatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "publisharticlestatus",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "article_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "setting_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "status",
            sa.VARCHAR(),
            server_default=sa.text("'PENDING'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status_text", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "try_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["article.id"],
            name="publisharticlestatus_article_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["setting_id"],
            ["setting.id"],
            name="publisharticlestatus_setting_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="publisharticlestatus_pkey"),
        sa.UniqueConstraint(
            "article_id", "setting_id", name="unique_article_setting"
        ),
    )
    op.drop_table("publish_article_status")
    # ### end Alembic commands ###
