"""feat: add unique constraint to PublishArticleStatus model

Revision ID: e8763fd0e264
Revises: 48d0bd5f41db
Create Date: 2023-12-24 16:49:50.665665

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8763fd0e264"
down_revision: Union[str, None] = "48d0bd5f41db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "publisharticlestatus",
        "publish_status",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.create_unique_constraint(
        "unique_article_setting",
        "publisharticlestatus",
        ["article_id", "setting_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "unique_article_setting", "publisharticlestatus", type_="unique"
    )
    op.alter_column(
        "publisharticlestatus",
        "publish_status",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###
