"""feat: add unique name and url to Project model

Revision ID: eb5a13f9c615
Revises: 9336e230e3b5
Create Date: 2023-12-18 15:06:11.356414

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb5a13f9c615"
down_revision: Union[str, None] = "9336e230e3b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_name_url", "project", ["name", "url"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_name_url", "project", type_="unique")
    # ### end Alembic commands ###
