"""refactor: Project model article element fields - 4

Revision ID: fc3b8084efb5
Revises: 05648e9c5742
Create Date: 2023-12-22 13:06:23.364279

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc3b8084efb5"
down_revision: Union[str, None] = "05648e9c5742"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "parse_last_article_count",
            sa.Integer(),
            nullable=False,
            server_default="10",
        ),
    )
    op.execute(
        "UPDATE project SET parse_last_article_count = "
        "COALESCE(parse_last_article, 10)"
    )
    op.drop_column("project", "parse_last_article")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "parse_last_article",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("project", "parse_last_article_count")
    # ### end Alembic commands ###
