name: CI BE
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.4
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Injecting env vars
        run: |
          echo "${{ secrets.ENV_SECRETS }}" >> .env

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.11
          cache: true

      - name: Install dependencies
        run: pdm install --dev

      - name: Install pre-commit
        uses: pre-commit/action@v3.0.0
