name: CI FE
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Install Node.js and npm
        run: sudo apt-get install -y nodejs npm

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install npm dependencies in frontend
        run: |
          cd frontend
          npm install --dev
          cd -

      - name: Install pre-commit
        uses: pre-commit/action@v3.0.0
